#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# setup.sh — Manage a self-hosted Neon stack.
# Run from the docker-compose/ directory:
#   bash setup.sh
# Re-running is safe (idempotent where possible).
# -----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

CONFIG_JSON="$SCRIPT_DIR/compute_wrapper/var/db/postgres/configs/config.json"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✔ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
die()     { echo -e "${RED}✖ $*${NC}" >&2; exit 1; }
header()  { echo -e "\n${BOLD}━━━ $* ━━━${NC}"; }

# ── Helpers ───────────────────────────────────────────────────────────────────
need_sudo() { [[ $EUID -ne 0 ]] && sudo "$@" || "$@"; }

prompt() {
    local var="$1" msg="$2" default="${3:-}"
    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${BOLD}${msg}${NC} [${default}]: ")" val
        printf -v "$var" '%s' "${val:-$default}"
    else
        read -rp "$(echo -e "${BOLD}${msg}${NC}: ")" val
        printf -v "$var" '%s' "$val"
    fi
}

prompt_password() {
    local var="$1" msg="$2"
    while true; do
        read -rsp "$(echo -e "${BOLD}${msg}${NC}: ")" pw1; echo
        read -rsp "$(echo -e "${BOLD}Confirm password${NC}: ")" pw2; echo
        if [[ "$pw1" == "$pw2" && -n "$pw1" ]]; then
            printf -v "$var" '%s' "$pw1"; break
        fi
        warn "Passwords do not match or empty, try again."
    done
}

md5_pg_password() {
    python3 -c "import hashlib,sys; print(hashlib.md5((sys.argv[1]+sys.argv[2]).encode()).hexdigest())" "$1" "$2"
}

json_set_password() {
    python3 - "$1" "$2" <<'EOF'
import json, sys
path, new_hash = sys.argv[1], sys.argv[2]
with open(path) as f: data = json.load(f)
for role in data["spec"]["cluster"]["roles"]:
    if role["name"] == "cloud_admin":
        role["encrypted_password"] = new_hash
with open(path, "w") as f: json.dump(data, f, indent=4)
EOF
}

json_add_databases() {
    python3 - "$1" "${@:2}" <<'EOF'
import json, sys
path, names = sys.argv[1], sys.argv[2:]
with open(path) as f: data = json.load(f)
existing = {d["name"] for d in data["spec"]["cluster"]["databases"]}
added = []
for name in names:
    if name not in existing:
        data["spec"]["cluster"]["databases"].append(
            {"name": name, "owner": "cloud_admin", "options": None})
        added.append(name)
with open(path, "w") as f: json.dump(data, f, indent=4)
all_dbs = [d["name"] for d in data["spec"]["cluster"]["databases"]]
print(f"Added: {added}" if added else "No new databases (all already exist).")
print(f"All databases: {all_dbs}")
EOF
}

json_list_databases() {
    python3 - "$1" <<'EOF'
import json, sys
with open(sys.argv[1]) as f: data = json.load(f)
for d in data["spec"]["cluster"]["databases"]: print(f"  {d['name']}")
EOF
}

read_env_password() {
    # Extract password from existing .env POSTGRES_URL, or return empty
    [[ -f "$ENV_FILE" ]] || { echo ""; return; }
    grep "^POSTGRES_URL=" "$ENV_FILE" 2>/dev/null \
        | sed 's|.*cloud_admin:\([^@]*\)@.*|\1|' || echo ""
}

read_env_host() {
    [[ -f "$ENV_FILE" ]] || { echo "localhost"; return; }
    grep "^POSTGRES_URL=" "$ENV_FILE" 2>/dev/null \
        | sed 's|.*@\([^:]*\):.*|\1|' || echo "localhost"
}

write_env() {
    local host="$1" pw="$2" ssl_mode="$3" pg_version="$4" primary_db="$5"
    cat > "$ENV_FILE" <<EOF
# Neon Docker Compose — generated by setup.sh
# Edit manually or re-run setup.sh to regenerate.

REPOSITORY=ghcr.io/neondatabase
TAG=latest
PG_VERSION=${pg_version}
PARALLEL_COMPUTES=1

TENANT_ID=
TIMELINE_ID=

POSTGRES_URL=postgresql://cloud_admin:${pw}@${host}:55433/${primary_db}?sslmode=${ssl_mode}
POSTGRES_URL_UNPOOLED=postgresql://cloud_admin:${pw}@${host}:55433/${primary_db}?sslmode=${ssl_mode}

# neon-test-extensions profile only
PGUSER=cloud_admin
PGPASSWORD=${pw}
EOF
}

print_summary() {
    local host="$1" pw="$2" ssl_mode="$3"
    echo
    echo -e "${BOLD}Connection details:${NC}"
    echo -e "  Host:     ${CYAN}${host}:55433${NC}"
    echo -e "  User:     ${CYAN}cloud_admin${NC}"
    echo -e "  Password: ${CYAN}${pw}${NC}"
    echo -e "  SSL:      ${CYAN}${ssl_mode}${NC}"
    echo
    echo -e "${BOLD}Databases:${NC}"
    json_list_databases "$CONFIG_JSON"
    echo
    echo -e "${BOLD}Useful commands:${NC}"
    echo -e "  ${YELLOW}docker compose logs -f compute1${NC}     — live compute logs"
    echo -e "  ${YELLOW}docker compose ps${NC}                   — container health"
    echo -e "  ${YELLOW}docker compose restart compute1${NC}     — re-apply config.json changes"
    echo -e "  ${YELLOW}docker compose down -v${NC}              — full wipe"
}

# ── Prerequisites (always run) ────────────────────────────────────────────────
header "Prerequisites"

[[ -f "$CONFIG_JSON" ]] || die "config.json not found. Run this script from the docker-compose/ directory."

if ! command -v apt-get &>/dev/null; then
    die "This script requires apt-get (Ubuntu/Debian)."
fi

need_sudo apt-get update -qq

for pkg_cmd in "git:git" "python3:python3"; do
    pkg="${pkg_cmd%%:*}"; cmd="${pkg_cmd##*:}"
    command -v "$cmd" &>/dev/null \
        && success "$cmd present." \
        || { info "Installing $pkg…"; need_sudo apt-get install -y "$pkg"; success "$pkg installed."; }
done

if ! command -v docker &>/dev/null; then
    info "Installing docker.io…"
    need_sudo apt-get install -y docker.io docker-compose-plugin
    need_sudo systemctl enable --now docker
    success "Docker installed."
else
    success "docker present."
fi

if ! docker compose version &>/dev/null; then
    need_sudo apt-get install -y docker-compose-plugin
fi
success "docker compose $(docker compose version --short) ready."

if ! groups "$USER" | grep -q docker 2>/dev/null; then
    warn "Adding $USER to docker group (takes effect on next login / newgrp docker)."
    need_sudo usermod -aG docker "$USER"
fi

# ── Main menu ─────────────────────────────────────────────────────────────────
header "What would you like to do?"
echo
echo -e "  ${BOLD}[1]${NC} New instance setup  — full setup from scratch"
echo -e "  ${BOLD}[2]${NC} Add database(s)     — add to existing running instance"
echo -e "  ${BOLD}[3]${NC} Change password      — update cloud_admin password"
echo
read -rp "$(echo -e "${BOLD}Choice [1/2/3]${NC}: ")" CHOICE
CHOICE="${CHOICE:-1}"

# =============================================================================
# Option 2: Add databases only
# =============================================================================
if [[ "$CHOICE" == "2" ]]; then
    header "Add Databases"

    echo
    info "Existing databases:"
    json_list_databases "$CONFIG_JSON"
    echo
    prompt DB_INPUT "New database name(s) to add (space-separated)"
    # shellcheck disable=SC2206
    DB_ARRAY=($DB_INPUT)

    json_add_databases "$CONFIG_JSON" "${DB_ARRAY[@]}"
    success "config.json updated."

    if docker compose ps compute1 2>/dev/null | grep -q "Up"; then
        info "Restarting compute to apply changes…"
        docker compose restart compute1
        info "Waiting for compute…"
        TIMEOUT=60; ELAPSED=0
        printf "Waiting"
        until docker compose logs compute_is_ready 2>/dev/null | grep -q "accepting connections" \
              || docker compose logs compute1 2>/dev/null | grep -q "compute_monitor"; do
            [[ $ELAPSED -ge $TIMEOUT ]] && { echo; die "Timeout. Check: docker compose logs compute1"; }
            printf "."; sleep 2; ELAPSED=$((ELAPSED+2))
        done
        echo
        success "Compute restarted."
    else
        warn "Compute is not running. Start the stack with: docker compose up -d"
    fi

    echo
    info "Current databases:"
    json_list_databases "$CONFIG_JSON"
    exit 0
fi

# =============================================================================
# Option 3: Change password only
# =============================================================================
if [[ "$CHOICE" == "3" ]]; then
    header "Change cloud_admin Password"

    EXISTING_PW="$(read_env_password)"
    HOST="$(read_env_host)"

    prompt_password PG_PW "New password for cloud_admin"
    PG_HASH=$(md5_pg_password "$PG_PW" "cloud_admin")
    json_set_password "$CONFIG_JSON" "$PG_HASH"
    success "config.json updated (hash: ${PG_HASH:0:8}…)."

    # Update .env URLs in-place (keep everything else)
    if [[ -f "$ENV_FILE" ]]; then
        sed -i "s|cloud_admin:[^@]*@|cloud_admin:${PG_PW}@|g" "$ENV_FILE"
        sed -i "s|^PGPASSWORD=.*|PGPASSWORD=${PG_PW}|" "$ENV_FILE"
        success ".env updated."
    fi

    if docker compose ps compute1 2>/dev/null | grep -q "Up"; then
        info "Restarting compute to apply new password…"
        docker compose restart compute1
        TIMEOUT=60; ELAPSED=0
        printf "Waiting"
        until docker compose logs compute1 2>/dev/null | grep -q "compute_monitor"; do
            [[ $ELAPSED -ge $TIMEOUT ]] && { echo; die "Timeout."; }
            printf "."; sleep 2; ELAPSED=$((ELAPSED+2))
        done
        echo
        success "Password active."
    else
        warn "Compute is not running. Password will apply on next start."
    fi

    echo -e "\n${BOLD}New password:${NC} ${CYAN}${PG_PW}${NC}"
    exit 0
fi

# =============================================================================
# Option 1: Full new instance setup
# =============================================================================
header "New Instance Setup"

# ── Collect config ────────────────────────────────────────────────────────────
echo
prompt HOST "Server hostname or domain" "$(read_env_host)"

echo
EXISTING_PW="$(read_env_password)"
if [[ -n "$EXISTING_PW" && "$EXISTING_PW" != "cloud_admin" ]]; then
    warn "Password already set in .env. Press Enter to keep it."
    read -rsp "$(echo -e "${BOLD}New password${NC} [keep existing]: ")" PG_PW; echo
    PG_PW="${PG_PW:-$EXISTING_PW}"
else
    prompt_password PG_PW "Password for cloud_admin"
fi

echo
info "Existing databases:"
json_list_databases "$CONFIG_JSON"
echo
info "Enter additional database names to create (space-separated, or Enter to skip)."
read -rp "$(echo -e "${BOLD}Add databases${NC}: ")" DB_INPUT
# shellcheck disable=SC2206
DB_ARRAY=($DB_INPUT)

echo
SSL_SETUP="n"
CF_TUNNEL="n"
if [[ "$HOST" != "localhost" && "$HOST" != "127.0.0.1" ]]; then
    read -rp "$(echo -e "${BOLD}Set up nginx + Let's Encrypt SSL for ${HOST}?${NC} [y/N]: ")" SSL_SETUP
    if [[ "${SSL_SETUP,,}" == "y" ]]; then
        echo
        warn "HTTP-01 challenge requires port 80 to be reachable from the internet."
        warn "If you use a Cloudflare Zero Trust TCP tunnel (tcp://host:port), port 80"
        warn "is not exposed and HTTP-01 will fail. Use DNS-01 instead."
        echo
        read -rp "$(echo -e "${BOLD}Are you behind a Cloudflare tunnel (use DNS-01 challenge)?${NC} [y/N]: ")" CF_TUNNEL
    fi
fi

prompt PG_VERSION "Postgres version (14 15 16 17)" "16"

# ── Update config.json ────────────────────────────────────────────────────────
header "Updating Postgres spec"

PG_HASH=$(md5_pg_password "$PG_PW" "cloud_admin")
json_set_password "$CONFIG_JSON" "$PG_HASH"
success "Password hash updated (${PG_HASH:0:8}…)."

if [[ ${#DB_ARRAY[@]} -gt 0 ]]; then
    json_add_databases "$CONFIG_JSON" "${DB_ARRAY[@]}"
    success "Databases updated."
fi

# ── Write .env ────────────────────────────────────────────────────────────────
header "Writing .env"

SSL_MODE="disable"
[[ "${SSL_SETUP,,}" == "y" ]] && SSL_MODE="require"

PRIMARY_DB=$(python3 -c "
import json, sys
with open('$CONFIG_JSON') as f: d = json.load(f)
dbs = d['spec']['cluster']['databases']
print(dbs[0]['name'] if dbs else 'postgres')
")

write_env "$HOST" "$PG_PW" "$SSL_MODE" "$PG_VERSION" "$PRIMARY_DB"
success ".env written (primary db: ${PRIMARY_DB})."

# ── nginx + SSL ───────────────────────────────────────────────────────────────
if [[ "${SSL_SETUP,,}" == "y" ]]; then
    header "nginx + Let's Encrypt SSL"

    info "Installing nginx, stream module, certbot…"
    need_sudo apt-get install -y nginx libnginx-mod-stream certbot

    # ── HTTP site for certbot webroot challenge ────────────────────────────
    info "Configuring nginx HTTP site for ${HOST}…"
    need_sudo tee /etc/nginx/sites-available/neon > /dev/null <<NGINX
server {
    listen 80;
    server_name ${HOST};

    # Let's Encrypt webroot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Drop everything else on port 80
    location / {
        return 444;
    }
}
NGINX

    need_sudo ln -sf /etc/nginx/sites-available/neon /etc/nginx/sites-enabled/neon
    need_sudo rm -f /etc/nginx/sites-enabled/default
    need_sudo mkdir -p /var/www/html

    # ── Stream block: proxy port 5432 → 55433 ─────────────────────────────
    # nginx stream blocks must live outside the http {} context.
    # We append to a separate file included from nginx.conf.
    STREAM_CONF="/etc/nginx/neon-stream.conf"
    if ! grep -q "neon-stream.conf" /etc/nginx/nginx.conf; then
        info "Adding stream proxy (5432 → 55433)…"
        need_sudo tee "$STREAM_CONF" > /dev/null <<STREAM
stream {
    # Proxy the standard Postgres port to Neon compute.
    # Clients can connect on port 5432 instead of 55433.
    # Postgres handles TLS itself — nginx just passes bytes through.
    server {
        listen 5432;
        proxy_pass 127.0.0.1:55433;
        proxy_connect_timeout 10s;
        proxy_timeout 600s;
    }
}
STREAM
        # Append include at the end of nginx.conf (outside http block)
        need_sudo bash -c "echo 'include /etc/nginx/neon-stream.conf;' >> /etc/nginx/nginx.conf"
    else
        success "Stream proxy already configured."
    fi

    need_sudo nginx -t
    need_sudo systemctl enable --now nginx
    need_sudo systemctl reload nginx
    success "nginx running."

    # ── Get certificate ────────────────────────────────────────────────────
    CERT_DIR="$SCRIPT_DIR/certs"
    mkdir -p "$CERT_DIR"

    if need_sudo certbot certificates 2>/dev/null | grep -q "Domains:.*${HOST}"; then
        warn "Certificate for ${HOST} already exists, skipping issuance."
    elif [[ "${CF_TUNNEL,,}" == "y" ]]; then
        # DNS-01 challenge via Cloudflare API — no port 80 needed
        info "Installing certbot-dns-cloudflare…"
        need_sudo apt-get install -y python3-certbot-dns-cloudflare

        echo
        info "You need a Cloudflare API token with 'DNS:Edit' permission for ${HOST}."
        info "Create one at: https://dash.cloudflare.com/profile/api-tokens"
        info "Use the 'Edit zone DNS' template and scope it to your zone."
        echo
        prompt CF_API_TOKEN "Cloudflare API token"

        CF_CREDS_FILE="$HOME/.cloudflare/cloudflare.ini"
        mkdir -p "$HOME/.cloudflare"
        cat > "$CF_CREDS_FILE" <<CF_INI
# Cloudflare API token for certbot DNS-01 challenge
dns_cloudflare_api_token = ${CF_API_TOKEN}
CF_INI
        chmod 600 "$CF_CREDS_FILE"
        success "Credentials saved to ${CF_CREDS_FILE}."

        info "Obtaining Let's Encrypt certificate via DNS-01 for ${HOST}…"
        need_sudo certbot certonly \
            --dns-cloudflare \
            --dns-cloudflare-credentials "$CF_CREDS_FILE" \
            --dns-cloudflare-propagation-seconds 30 \
            -d "$HOST" \
            --non-interactive --agree-tos --register-unsafely-without-email
    else
        info "Obtaining Let's Encrypt certificate via HTTP-01 for ${HOST}…"
        need_sudo certbot certonly --webroot -w /var/www/html -d "$HOST" \
            --non-interactive --agree-tos --register-unsafely-without-email
    fi

    # ── Copy certs for Postgres (uid 1000 = postgres in container) ────────
    info "Copying certs (uid 1000)…"
    need_sudo cp "/etc/letsencrypt/live/${HOST}/fullchain.pem" "$CERT_DIR/server.crt"
    need_sudo cp "/etc/letsencrypt/live/${HOST}/privkey.pem"   "$CERT_DIR/server.key"
    need_sudo chown 1000:1000 "$CERT_DIR/server.crt" "$CERT_DIR/server.key"
    need_sudo chmod 644 "$CERT_DIR/server.crt"
    need_sudo chmod 600 "$CERT_DIR/server.key"
    success "Certs installed in ${CERT_DIR}."

    # ── Renewal hook ───────────────────────────────────────────────────────
    HOOK_DST="/etc/letsencrypt/renewal-hooks/deploy/neon-postgres.sh"
    sed "s|neon.ixa.ink|${HOST}|g; s|/home/soulwax/neon/docker-compose|${SCRIPT_DIR}|g" \
        "$SCRIPT_DIR/renew-certs.sh" > /tmp/neon-postgres-hook.sh
    need_sudo cp /tmp/neon-postgres-hook.sh "$HOOK_DST"
    need_sudo chmod +x "$HOOK_DST"
    success "Renewal hook installed at ${HOOK_DST}."

    # For DNS-01 renewals the Cloudflare credentials file must be readable by
    # root (certbot runs as root during renewal). Copy it to /etc/letsencrypt/
    # so it persists system-wide regardless of which user originally ran setup.
    if [[ "${CF_TUNNEL,,}" == "y" ]]; then
        need_sudo cp "$HOME/.cloudflare/cloudflare.ini" /etc/letsencrypt/cloudflare.ini
        need_sudo chmod 600 /etc/letsencrypt/cloudflare.ini
        # Ensure the renewal config points at the system-wide credentials file
        RENEWAL_CONF="/etc/letsencrypt/renewal/${HOST}.conf"
        if [[ -f "$RENEWAL_CONF" ]]; then
            need_sudo sed -i "s|dns_cloudflare_credentials.*|dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini|" "$RENEWAL_CONF"
        fi
        success "Cloudflare credentials installed at /etc/letsencrypt/cloudflare.ini."
    fi

    info "Testing renewal (dry run)…"
    need_sudo certbot renew --dry-run --quiet && success "Auto-renewal OK."

    # Update .env to use port 5432 now that stream proxy is active
    sed -i "s|:55433/|:5432/|g" "$ENV_FILE"
    info "Updated .env to use port 5432 (via nginx stream proxy)."
fi

# ── Clean stale pageserver state ──────────────────────────────────────────────
header "Checking pageserver state"

for p in "$SCRIPT_DIR/pageserver_config/tenants" \
          "$SCRIPT_DIR/pageserver_config/deletion" \
          "$SCRIPT_DIR/pageserver_config/pageserver.pid"; do
    [[ -e "$p" ]] && { rm -rf "$p"; warn "Removed stale: $p"; }
done
success "Pageserver state clean."

# ── Start the stack ───────────────────────────────────────────────────────────
header "Starting the stack"

if docker compose ps -q 2>/dev/null | grep -q .; then
    info "Stopping existing containers…"
    docker compose down
fi

info "Building compute wrapper and starting all services…"
PG_VERSION="$PG_VERSION" docker compose up --build -d 2>&1 \
    | grep -v "^time=" | grep -v "^#" | grep -E "Built|Started|Error|error" || true
success "Stack started."

# ── Wait for compute ──────────────────────────────────────────────────────────
header "Waiting for compute"

TIMEOUT=120; ELAPSED=0
printf "Waiting"
until docker compose logs compute_is_ready 2>/dev/null | grep -q "All computes are started"; do
    if [[ $ELAPSED -ge $TIMEOUT ]]; then
        echo
        die "Timeout after ${TIMEOUT}s. Debug with: docker compose logs compute1"
    fi
    printf "."; sleep 2; ELAPSED=$((ELAPSED+2))
done
echo
success "Compute is ready!"

# ── Summary ───────────────────────────────────────────────────────────────────
header "Done"

print_summary "$HOST" "$PG_PW" "$SSL_MODE"

if [[ "${SSL_SETUP,,}" == "y" ]]; then
    echo -e "  ${YELLOW}Port 5432${NC} → nginx stream → 55433 (standard Postgres port active)"
    if [[ "${CF_TUNNEL,,}" == "y" ]]; then
        echo -e "  ${YELLOW}SSL cert${NC}  — DNS-01 via Cloudflare (no port 80 required)"
        echo -e "  ${YELLOW}Renewal${NC}   — certbot will use Cloudflare API token automatically"
    else
        echo -e "  ${YELLOW}Port 80${NC}   → nginx (certbot webroot renewals)"
    fi
    echo
fi

if [[ "${SSL_SETUP,,}" != "y" && "$HOST" != "localhost" ]]; then
    warn "SSL not enabled. Re-run setup.sh and choose option 1 to add SSL."
fi
